### ISSUE TITLE
☸️ Can not run in Kubernetes?

### ISSUE THREAD

**Issue by hardy4yooz** [Zenika/alpine-chrome#109]
**Describe the bug**
Can this image run in Kubernetes? I got this error.

```
[0730/093334.582068:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
DevTools listening on ws://0.0.0.0:9222/devtools/browser/ffc8216e-74e1-4005-a9c6-5fae589bb301
[0730/093334.599757:ERROR:zygote_host_impl_linux.cc(262)] Failed to adjust OOM score of renderer with pid 26: Permission denied (13)
[0730/093334.608738:ERROR:zygote_host_impl_linux.cc(262)] Failed to adjust OOM score of renderer with pid 28: Permission denied (13)
[0730/093334.807594:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
```

**Comment by jlandure** [comment]
Hi @hardy4yooz 

Thanks for your issue! 👍 
Sorry for the delay. 😊

I think you have a problem using the sandbox mechanism of Chromium. [Please read this section of the README](https://github.com/Zenika/alpine-chrome#3-ways-to-securely-use-chrome-headless-with-this-image).
What method did you use? `--no-sandbox` or `SYS_ADMIN` or `seccomp`?

In this [chromium page](https://bugs.chromium.org/p/chromium/issues/detail?id=576409), they indicate to test it -- `You can give CAP_DAC_OVERRIDE to your process` 🐛 

I have to create an example using Kubernetes.
If you're interested, you can help to create it in the [example folder](https://github.com/Zenika/alpine-chrome/tree/master/examples). 🚀

**Comment by simonfrey** [comment]
Have the same problem. Running alpine-chrome in k8s fails. I choose to go with SYS_ADMIN caps and the default entry point:

```yaml
...
  containers:
      - args:
        - --remote-debugging-address=0.0.0.0
        - --remote-debugging-port=9222
        image: zenika/alpine-chrome
        name: zenika-alpine-chrome
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 1
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_ADMIN
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/chrome
          name: chrome
...
```
The volume mounts are temporary volumes

Already tried following and that did not help:
- add `DAC_OVERRIDE` to the CAP add section 
- run with `--no-sandbox`
- run with custom args dropping the `--disable-software-rasterizer` arg

**Comment by simonfrey** [comment]
The following issue might be a fix for this? #8

**Comment by jlandure** [comment]
Hi @simonfrey 👋 

First, thanks for your time! 👍 

I don't know if it could work! I will take some time to investigate it.

Can you share your K8S example in a PR in the [`examples` folder](https://github.com/Zenika/alpine-chrome/tree/master/examples)? If you wait for October, your PR will count for **hacktoberfest** 🎉 

[Like I said, have you tested this?](https://github.com/Zenika/alpine-chrome/issues/109#issuecomment-677774488)
> In this chromium page, they indicate to test it -- You can give CAP_DAC_OVERRIDE to your process 🐛

**Comment by simonfrey** [comment]
Yes I tried the CAP_DAV_OVERIDE and the same error still occurs

**Comment by jlandure** [comment]
Hi @simonfrey 

Ok! thanks for the reply 😊

**Comment by simonfrey** [comment]
> Can you share your K8S example in a PR in the [`examples` folder](https://github.com/Zenika/alpine-chrome/tree/master/examples)? If you wait for October, your PR will count for **hacktoberfest** tada

I will build an example :D Would you be so kind and add the hacktoberfest label so it counts into it :D

**Comment by jlandure** [comment]
Hey @simonfrey 👋 

Yes, I added the label. 👍

**Comment by CyberHippo** [comment]
Hi all,

Thank you for your great work on this image and the [example for k8s](https://github.com/Zenika/alpine-chrome/blob/master/examples/k8s/deployment.yml)!

I tried to run your example and I still got the following logs: 

```
[1104/165305.104292:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[1104/165305.105255:WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.

DevTools listening on ws://0.0.0.0:9222/devtools/browser/f329a418-3587-4c65-b945-10e988b38f7f
[1104/165305.171139:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 24: Permission denied (13)
[1104/165305.270101:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 31: Permission denied (13)
[1104/165305.583951:WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
```

Is there a way to suppress them ? 

Note that the pod is running fine and I can use the service without error.

**Comment by stanislav-zaprudskiy** [comment]
Same here. Pod specs are:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    ...
    spec:
      containers:
      ...
      - args:
        - --remote-debugging-port=9222
        - --remote-debugging-address=0.0.0.0
        - --headless
        - --disable-gpu
        image: zenika/alpine-chrome:83
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /json/version
            port: 9222
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: chrome
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /json/version
            port: 9222
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SYS_ADMIN
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/chrome
          name: chrome
      ...
      volumes:
      - emptyDir: {}
        name: tmp
      - emptyDir: {}
        name: chrome
```

Logs are:

```
1120/070843.509846:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
[1120/070843.544823:ERROR:zygote_host_impl_linux.cc(262)] Failed to adjust OOM score of renderer with pid 27: Permission denied (13)

DevTools listening on ws://0.0.0.0:9222/devtools/browser/dde29cea-4f5e-44ef-a256-7968f81a8620
[1120/070843.677471:ERROR:zygote_host_impl_linux.cc(262)] Failed to adjust OOM score of renderer with pid 38: Permission denied (13)
[1120/070843.722710:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
```

I also tried setting `--no-sandbox` arg instead of configuring volumes and securityContext but without any luck.

Kubernetes version is `1.14`, and I tried both `zenika/alpine-chrome:83` and `zenika/alpine-chrome:86`.

@simonfrey, can you please explain on `securityContext`'s `allowPrivilegeEscalation: false` together with adding `CAP_SYS_ADMIN`? From what I see in the documentation, these two are competing with each other:
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/no-new-privs.md#changes-of-securitycontext-objects
* https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
