### ISSUE TITLE
How to deploy python app with google chrome and chromedriver ?

### ISSUE THREAD

**Issue by gavrilka** [Zenika/alpine-chrome#151]
I am glad to find this source, i have a feeling to solve my 2 weeks unsolvable problem.
Running python app on AWS Ubuntu 20.04, that uses arsenic library (same to puppeteer). This library requires browser and driver for work. I Tested my python code on windows via PyCharm, with installed google chrome and chromedriver in source folder, and all works perfect. But i can't understand how to make it work with docker.
If really i am bad with docker...
I have a dockerfile, docker-compose.yml, launching app in ubuntu terminal with docker-compose up --build and my app builds and runs. 2 weeks i was trying to add chrome and chromedriver installation inside my app, editing dockerfile and docker-compose. But now after seeing this repo i have a feeling that i just need to run 3rd part container running correct code in terminal..
I will be very happy is someone could me help, i am so stuck with this trouble...
Dockerfile:

```
FROM python:latest
WORKDIR /src
COPY requirements.txt /src
RUN pip install -r requirements.txt
COPY . /src
```
docker-compose.yml

```
version: '3.1'

services:

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    environment:
      WEBAPP_PORT: 3001
    env_file:
      - ".env"
    ports:
      - 8443:3001
    networks:
      - botnet
    volumes:
      - ./:/src

networks:
      botnet:
        driver: bridge
```

P.S. before i was using selenium + phantomJS, and i had to add phantomJS image container as one more service in docker-compose.yml Maybe i am again wrong and should find correct chrome image for docker-compose.yml ?
