### ISSUE TITLE
GCP Cloud Build: EACCES: permission denied, mkdir '/workspace/node_modules'

### ISSUE THREAD

**Issue by nguyenxndaidev** [Zenika/alpine-chrome#181]
**Describe the bug**

I have this error on GCP Cloud Build:

```
error Could not write file "/workspace/yarn-error.log": "EACCES: permission denied, open '/workspace/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/workspace/node_modules'".
```

**To Reproduce**

1. `cloudbuild.yaml`

```
steps:
  - name: zenika/alpine-chrome:89-with-node-14
    dir: '/usr/src/app'
    entrypoint: yarn
    args: [ 'install' ]
```

2. Run the build on GCP Cloud Build, I got error message:

```
error Could not write file "/workspace/yarn-error.log": "EACCES: permission denied, open '/workspace/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/workspace/node_modules'".
```

**Additional context**
Running locally with Docker for Windows on my machine, everything is fine.
