### ISSUE TITLE
[Help-Wanted] How to run chrome in docker like `jlesage/firefox`

### ISSUE THREAD

**Issue by xiongjiamu** [Zenika/alpine-chrome#229]
HI, guys

I am not very familiar to this project yet, my intention is run a docker version chrome on my server, like the jlesage/firefox works with this `docker-compse` below:

```yaml
version: '3.3'
services:
    firefox:
        container_name: firefox
        ports:
            - '8081:5800'
        volumes:
            - '/docker/appdata/firefox:/config:rw'
        image: 'jlesage/firefox:latest'
```

I tried this example docker-compose file `https://github.com/Zenika/alpine-chrome/blob/master/examples/docker-compose/docker-compose.yml` , but it didn't worked out, can anyone help me, thanks ~
