### ISSUE TITLE
Path undefined on Alpine Linux 3.20 with docker compose

### ISSUE THREAD

**Issue by robvanvolt** [Zenika/alpine-chrome#259]
**Describe the bug**
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "chromium-browser": executable file not found in $PATH: unknown`

**To Reproduce**

```
services:
  chrome:
    image: eu.gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    container_name: chrome
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
```

`doas docker compose up -d`

**What is the expected behavior?**

The container starting correctly.

**What is the actual behavior?**

See above error message.

**Possible solution**

I have already tried other images without success.

Also, the minimum example does not work:

```
docker container run -it --rm zenika/alpine-chrome
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "chromium-browser": executable file not found in $PATH: unknown.
```

Am i missing any dependencies?
