### ISSUE TITLE
chrome-1 exited with code 133

### ISSUE THREAD

**Issue by Targunitoth** [Zenika/alpine-chrome#261]
**Describe the bug**
I have the same bug as https://github.com/hoarder-app/hoarder/issues/881

I only get `chrome-1 exited with code 133`, without other debugging information

**To Reproduce**
I just started your minimal example (https://github.com/jlandure/alpine-chrome/blob/master/examples/docker-compose/docker-compose.yml) to repoduce the problem:

```
root@main-server:/opt/tmp$ docker image inspect --format='{{index .RepoDigests 0}}' zenika/alpine-chrome
zenika/alpine-chrome@sha256:e423ce79879fdceecb8481699312b90976a9bc91162814807e578086514d0a65
root@main-server:/opt/tmp$ docker-compose up
[+] Running 2/0
 ⠿ Container tmp-chrome-1  Created                                                                                                                                                                        0.0s
 ⠿ Container tmp-nginx-1   Created                                                                                                                                                                        0.0s
Attaching to tmp-chrome-1, tmp-nginx-1
tmp-nginx-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
tmp-nginx-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
tmp-nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
tmp-nginx-1   | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
tmp-nginx-1   | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
tmp-nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
tmp-nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: using the "epoll" event method
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: nginx/1.27.3
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309)
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: OS: Linux 5.4.17-2136.333.5.1.el8uek.aarch64
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
tmp-nginx-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: start worker processes
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: start worker process 22
tmp-nginx-1   | 2025/01/19 14:59:26 [notice] 1#1: start worker process 23
tmp-chrome-1 exited with code 133
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 2/2
 ⠿ Container tmp-chrome-1  Stopped                                                                                                                                                                        0.0s
 ⠿ Container tmp-nginx-1   Stopped                                                                                                                                                                        0.2s
canceled
root@main-server:/opt/tmp$
```

**What is the expected behavior?**
Chrome should start

**What is the actual behavior?**
Chrome exits with error 133

**Possible solution**
Maybe somthing hardware related?
```
root@main-server:/opt/tmp$ uname -a
Linux main-server 5.4.17-2136.333.5.1.el8uek.aarch64 #3 SMP Fri Jul 12 13:11:54 PDT 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Versions**
`Docker Compose version v2.10.2`

**Comment by gilbrotheraway** [comment]
yeah i had to disable both chrome and meilisearch, you lose some features but it's also lighter, running it on openmediavault on rock-5b board

EDIT: screw that, search is not working

**Comment by gilbrotheraway** [comment]
please post your compose file, i believe i solved it

**Comment by Targunitoth** [comment]
I used the minimal example docker-compose file (https://github.com/jlandure/alpine-chrome/blob/master/examples/docker-compose/docker-compose.yml)

```
version: "2"
services:
  nginx:
    image: nginx:alpine
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - 80:80

  chrome:
    image: zenika/alpine-chrome:latest
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - "9222:9222"
        
```

**Comment by romansh** [comment]
I was getting 'exited with code 137' errors (not 133, though). Moving to the selenium/standalone-chromium Docker image immediately fixed the issue.  

But I wasted a few days trying to fix it, thinking the problem was in my code.

**Comment by DIGist** [comment]
Not sure if it will be true for everyone, but at least for me it seems like using the SECCOMP with chrome.json method (https://hub.docker.com/r/zenika/alpine-chrome) from the docker image page seems to have resolved my exit code 133 error on my x86 host.

```
  chrome:
#    image: gcr.io/zenika-hub/alpine-chrome:123
    image: gcr.io/zenika-hub/alpine-chrome:latest
    restart: always
    container_name: karakeep_chrome
    security_opt:
      - "seccomp=chrome.json"
    command:
#      - --no-sandbox
      - --disable-gpu
      - --headless
#test      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
```
